// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgZfDh9NFm8FJJCDNBAdsVahX6AJYQdeA',
    appId: '1:1066210387407:web:d18e6915919c912be91eba',
    messagingSenderId: '1066210387407',
    projectId: 'order-wise',
    authDomain: 'order-wise.firebaseapp.com',
    storageBucket: 'order-wise.appspot.com',
    measurementId: 'G-EDX6RTNW4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgflT8IqRm1CRdCnBBMd-DGtLal7ZnYIc',
    appId: '1:1066210387407:android:bce557da83da0d36e91eba',
    messagingSenderId: '1066210387407',
    projectId: 'order-wise',
    storageBucket: 'order-wise.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxo0zE_D3X6eWrqM0gZiVz2K4ain812gA',
    appId: '1:1066210387407:ios:b05aa225d6e8ad9fe91eba',
    messagingSenderId: '1066210387407',
    projectId: 'order-wise',
    storageBucket: 'order-wise.appspot.com',
    iosClientId: '1066210387407-jttnqkpo3aageu2l2osmc97llgmor2sv.apps.googleusercontent.com',
    iosBundleId: 'com.example.conuHacks2005',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxo0zE_D3X6eWrqM0gZiVz2K4ain812gA',
    appId: '1:1066210387407:ios:b05aa225d6e8ad9fe91eba',
    messagingSenderId: '1066210387407',
    projectId: 'order-wise',
    storageBucket: 'order-wise.appspot.com',
    iosClientId: '1066210387407-jttnqkpo3aageu2l2osmc97llgmor2sv.apps.googleusercontent.com',
    iosBundleId: 'com.example.conuHacks2005',
  );
}
